services:
    api:
      container_name: api
      restart: always
      build:
        context: .
        dockerfile: docker/local/backend/Dockerfile
      ports:
        - "3001:3000"
      volumes:
        - ./backend:/app
        - /app/node_modules 
      environment:
        - PORT=3000 
        - NODE_ENV=${NODE_ENV}
        - MONGO_URI=${MONGO_URI}
      depends_on:
        - mongo
      networks:
        - unipay
    
    frontend:
      container_name: frontend
      restart: always
      build:
        context: .
        dockerfile: docker/local/frontend/Dockerfile
      ports:
        - "4001:4000"
      volumes:
        - ./frontend:/app
        - /app/node_modules
        - /app/.next
      environment:
        - NODE_ENV=${NODE_ENV}
        - PORT=4000
      depends_on:
        - api
      networks:
        - unipay
    
    mongo:
      image: mongo:latest
      container_name: mongo
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      networks:
        - unipay
    
    mongo-express:
      image: mongo-express:latest
      container_name: mongo-express
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_BASICAUTH_PASSWORD=admin 
        - ME_CONFIG_BASICAUTH_USERNAME=admin
      depends_on:
        - mongo
      networks:
        - unipay
    
    mailhog:
      image: mailhog/mailhog:latest
      container_name: mailhog
      ports:
        - "1025:1025"
        - "8025:8025"
      networks:
        - unipay

networks:
  unipay:
    driver: bridge

volumes:
  mongo-data: