services:
    api-prod:
      container_name: api-prod
      restart: always
      build:
        context: .
        dockerfile: docker/prod/backend/Dockerfile
      ports:
        - "3001:3000"
      volumes:
        - ./backend:/app
      environment:
        - PORT=3000 
        - MONGO_URI=${MONGO_URI}
      env_file:
        - .backend.prod.env
      networks:
        - unipay-prod
    
    frontend-prod:
      container_name: frontend-prod
      build:
        context: .
        dockerfile: docker/prod/frontend/Dockerfile
      ports:
        - "4001:4000"
      volumes:
        - ./frontend:/app
      environment:
        - PORT=4000
      env_file:
        - .frontend.prod.env
      depends_on:
        - api-prod
      networks:
        - unipay-prod
    
    nginx-prod:
      container_name: nginx-prod
      restart: always
      build:
        context: .
        dockerfile: docker/prod/nginx/Dockerfile
      ports:
        - "8080:80"
      depends_on:
        - api-prod
        - frontend-prod
      networks:
        - unipay-prod

networks:
  unipay-prod:
    driver: bridge
